server:
  port: ${DOCKER_SERVER_PORT}
  address: ${DOCKER_SERVER_IP}
  shutdown: graceful
spring:
  rabbitmq:
    host: ${MQ_HOSTNAME}
    port: ${MQ_PORT}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    ssl:
      enabled: true
  application.name: ip-release-server
  config:
    import: "optional:configserver:http://${CONFIG_HOSTNAME}:${CONFIG_PORT}"
  cloud:
    config:
      uri: http://${CONFIG_HOSTNAME}:${CONFIG_PORT}
  profiles:
    active: prod
eureka:
  instance:
    hostname: ${server.address}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka/
logging.level:
    org.springframework.data.r2dbc: DEBUG